<?php

namespace AppBundle\Repository;

/**
 * OilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OilRepository extends \Doctrine\ORM\EntityRepository
{
}
